import Head from 'next/head';
import NextNProgress from 'nextjs-progressbar';
import { wrapper } from '../store';

import '../styles/globals.css';
import '../styles/antdstyles.css';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Mobile Case</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap"
          rel="stylesheet"
        />
      </Head>
      <NextNProgress />
      <Component {...pageProps} />
    </>
  );
}

export default wrapper.withRedux(MyApp);
